In [1]:
import numpy as np

## Array

### array type

In [2]:
array = np.array([1, 2, 3, 4, 5])
array
print(type(array))

<class 'numpy.ndarray'>


### making array from list

In [3]:
data = [1, 2, 3, 4, 5]
array = np.array(data)
array

array([1, 2, 3, 4, 5])

### dtype --> changing the item's type

In [4]:
array = np.array([1, 2, 3, 4, 5], dtype=np.float16)
array

array([1., 2., 3., 4., 5.], dtype=float16)

### astype --> changing the item's type

In [6]:
array = np.array([1, 2, 3, 4, 5]).astype(np.float32)
array

array([1., 2., 3., 4., 5.], dtype=float32)

### making a matrix

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).astype(np.int16)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

### matrix informations

In [9]:
print(matrix.ndim)
print(matrix.size)
print(matrix.shape)
print(matrix.dtype)

2
9
(3, 3)
int16


### array informations

In [11]:
print(array.ndim)
print(array.size)
print(array.shape)
print(array.dtype)

1
5
(5,)
float32


### array with 1 row

In [14]:
row = np.array([[1, 2, 3, 4, 5]])
print(row)
print(row.shape)
print(row.ndim)

[[1 2 3 4 5]]
(1, 5)
2


## arange --> making an array by a range of numbers (start, stop, step) >> stop not included

In [16]:
range_vector1 = np.arange(1, 10, 2)
print(range_vector1)

range_vector2 = np.arange(1, 10)
print(range_vector2)

range_vector3 = np.arange(1, 10, 0.6)
print(range_vector3)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[1.  1.6 2.2 2.8 3.4 4.  4.6 5.2 5.8 6.4 7.  7.6 8.2 8.8 9.4]


### arang vector

In [26]:
arange_vector = np.arange(1, 101, 1)
print(arange_vector)
print(arange_vector.ndim)
print(arange_vector.shape)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
1
(100,)


### arang matrix

In [27]:
arange_matrix = arange_vector.reshape((10, 10))
print(arange_matrix)
print(arange_matrix.shape)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
(10, 10)


## linspace --> making an array in a range of two number, divided to x slices >> (start, stop, number of slices)

In [17]:
lin = np.linspace(1, 20, 10)
lin

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

## Reshape

In [25]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(array)

print(array.shape)
print(array.size)

print(array.reshape((4, 3))) # array.reshape((4, -1)) --> 4 rows and any colums


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Ravel & Flatten ---> matrix to vector

In [29]:
print(arange_matrix.ravel()) # method

print(np.ravel(arange_matrix)) # function

print(arange_matrix.flatten()) # only method

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46

## Full & Full_Like  ---> making an array by one number

In [31]:
print(np.full((6, 4), 5)) # --> ((row, col) , filling num)

print(np.full_like(array, 10)) # --> get an exicting array and fill it with a fix number

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
