# Introduce Numpy

In [1]:
import numpy as np

In [2]:
# Numpy is used for numerical computing and array-based data analysis

# Creat array

In [3]:
# Creat a 1D array

In [4]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [5]:
# Creat a 2D array

In [6]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# List and array

In [8]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array([1, 2, 3, 4, 5])

In [9]:
# Numpy arrays supported fast vectorized operations

In [10]:
my_array *2

array([ 2,  4,  6,  8, 10])

In [11]:
# Python lists repeat when multiplied by a numbeer

In [12]:
my_list *2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# Array 

In [13]:
arr = np.array([[10, 20, 30],[40, 50, 60]])

In [14]:
# Number of dimensions

In [15]:
arr.ndim

2

In [16]:
# size of each dimension : (rows, columns)

In [17]:
arr.shape

(2, 3)

In [18]:
# Total number of elements

In [19]:
arr.size

6

In [20]:
# Dta type of elements

In [21]:
arr.dtype

dtype('int64')

In [23]:
print('ndim  : ', arr.ndim)
print('shape : ', arr.shape)
print('size  : ', arr.size)
print('dtype : ', arr.dtype)

ndim  :  2
shape :  (2, 3)
size  :  6
dtype :  int64


In [24]:
# ndarray = NumPy's main array object

In [25]:
type(arr)

numpy.ndarray