In [1]:
import numpy as np

In [2]:
vec1 = np.arange(1, 10)
print(vec1)
vec2 = np.arange(11, 20)
print(vec2)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


## hstack Vectors

In [3]:
np.hstack((vec1, vec2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

## Vstack Vectors

In [4]:
np.vstack((vec1, vec2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

## c_ Vectors

In [5]:
np.c_[vec1, vec2]

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

## hstack Matrix

In [8]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
print(array1)
print('-' *10)
print(array2)

[[1 2 3]
 [4 5 6]]
----------
[[ 7  8  9]
 [10 11 12]]


In [9]:
np.hstack((array1, array2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## vstack Matrix

In [10]:
np.vstack((array1, array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Concatenate

In [11]:
np.concatenate((array1, array2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [12]:
np.concatenate((array1, array2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])