In [1]:
import numpy as np

# Conditional Selecting 

In [2]:
scores = np.random.randint(5,20,(10,4))
scores

array([[18, 12,  5,  9],
       [17,  5, 13, 10],
       [11, 13, 15, 13],
       [ 7, 16,  7,  6],
       [ 9, 19, 12,  7],
       [19, 18, 15, 18],
       [12, 13,  5,  8],
       [ 8, 18, 17,  8],
       [17, 19, 14, 13],
       [ 8, 12,  8, 19]], dtype=int32)

## Masking

In [3]:
scores[True] # --> Select everything

array([[[18, 12,  5,  9],
        [17,  5, 13, 10],
        [11, 13, 15, 13],
        [ 7, 16,  7,  6],
        [ 9, 19, 12,  7],
        [19, 18, 15, 18],
        [12, 13,  5,  8],
        [ 8, 18, 17,  8],
        [17, 19, 14, 13],
        [ 8, 12,  8, 19]]], dtype=int32)

In [4]:
scores[[False, True, True, True, True, True, True, True, True, False]] # Select rows when True

array([[17,  5, 13, 10],
       [11, 13, 15, 13],
       [ 7, 16,  7,  6],
       [ 9, 19, 12,  7],
       [19, 18, 15, 18],
       [12, 13,  5,  8],
       [ 8, 18, 17,  8],
       [17, 19, 14, 13]], dtype=int32)

In [6]:
mask = scores > 17 # return True if condition is true in matrix
mask

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True,  True, False,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [7]:
scores[mask] # return only True values

array([18, 19, 19, 18, 18, 18, 19, 19], dtype=int32)

In [8]:
scores[scores > 17] # put the mask inside [] of matrix

array([18, 19, 19, 18, 18, 18, 19, 19], dtype=int32)

In [9]:
mask = (scores > 14) & (scores <= 17) # The () are really important, it doesn't work without them!
scores[mask]

 # or we can use:   scores[(scores > 14) & (scores <= 17)]

array([17, 15, 16, 15, 17, 17], dtype=int32)