In [1]:
import numpy as np

## Vector

In [3]:
vec01 = np.random.randint(1, 10, 10)
vec02 = np.random.randint(1, 10, 10)
print(vec01)
print(vec02)

[1 1 6 1 1 7 4 4 7 1]
[8 5 3 8 6 1 7 1 3 3]


## Hadamard

In [4]:
vec01 * vec02

array([ 8,  5, 18,  8,  6,  7, 28,  4, 21,  3], dtype=int32)

## Inner

In [5]:
np.inner(vec01, vec02)

np.int32(108)

## Dot

In [6]:
np.dot(vec01, vec02)

np.int32(108)

## Matrix

In [7]:
mat01 = np.array([[1, 2] , [3, 4]])
mat02 = np.array([[5, 6], [7, 8]])
print(mat01)
print(mat02)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


## Hadamard --> array * array

In [8]:
mat01 * mat02

array([[ 5, 12],
       [21, 32]])

## Inner --> Row * Row

In [10]:
np.inner(mat01, mat02)

array([[17, 23],
       [39, 53]])

## Dot --> Row * Column

In [11]:
np.dot(mat01, mat02)

array([[19, 22],
       [43, 50]])