## Random

In [1]:
import numpy as np

### random

In [6]:
array = np.random.random((4, 10)) (row, col) making random number betweeon 0 and 1 --> 1 is not included
array

array([[0.73822581, 0.37614987, 0.165189  , 0.29907286, 0.86360864,
        0.07283715, 0.47309932, 0.37376477, 0.7411461 , 0.76256938],
       [0.23727841, 0.58973421, 0.07691407, 0.14213393, 0.84351249,
        0.37897765, 0.18695095, 0.18833325, 0.45818082, 0.61328666],
       [0.16873555, 0.47290186, 0.76083431, 0.75202004, 0.19286815,
        0.79903703, 0.51576642, 0.61897766, 0.18576889, 0.23068135],
       [0.85872736, 0.71373984, 0.62736532, 0.44561784, 0.41425711,
        0.96800288, 0.24624581, 0.01753121, 0.14511195, 0.12034169]])

### rand

In [12]:
array = np.random.rand(10, 4) # (row, col) making random number betweeon 0 and 1 --> 1 is not included
array

array([[0.75425586, 0.69694433, 0.13076516, 0.17184928],
       [0.44259763, 0.64255814, 0.6089461 , 0.24874404],
       [0.02781651, 0.18744102, 0.58146273, 0.28265044],
       [0.93498359, 0.60177921, 0.32810145, 0.38164685],
       [0.03216817, 0.99039755, 0.42270893, 0.30743182],
       [0.79896695, 0.8505763 , 0.78126307, 0.90275897],
       [0.07442104, 0.01966371, 0.28569042, 0.4514911 ],
       [0.7788186 , 0.14247396, 0.41676728, 0.1910518 ],
       [0.6663926 , 0.03197647, 0.21966991, 0.1881478 ],
       [0.06752353, 0.80670792, 0.13584726, 0.79500423]])

In [13]:
vector = np.random.rand(10) # making an one row array y random numbers between 0 and 1 --> 1 is not included
vector

array([0.36670445, 0.73728096, 0.39618792, 0.34770078, 0.43636812,
       0.40198721, 0.89090791, 0.63142047, 0.72612409, 0.46792003])

### randint

In [15]:
array = np.random.randint(0, 20) # make a random number
array

11

In [16]:
array = np.random.randint(0, 20, 10) # make random number more than 1 --> (start, stop-1, how many number do you need!)
array

array([ 3,  6, 16, 11,  7, 13,  5,  7, 11,  3], dtype=int32)

In [17]:
array = np.random.randint(0, 20, (5,5)) # make a matrix of random numbers
array

array([[13,  1,  7,  2, 12],
       [ 9, 19,  2, 19, 16],
       [ 1,  0,  8,  0, 13],
       [ 5, 18,  2,  4,  1],
       [18,  1,  9, 15,  0]], dtype=int32)