In [1]:
import numpy as np

## List Slicing

In [3]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### numbers[start=0, stop-1= end, step=1]

In [4]:
numbers[0:6] # from index 0 to 6

[1, 2, 3, 4, 5, 6]

In [5]:
numbers[-3::] # from index -3 to the end

[8, 9, 10]

In [6]:
numbers[::] # everything

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
numbers[::-1] # from last to first

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

## Array Slicing

In [9]:
array = np.arange(12).reshape((3, 4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### array[Row, columns]
### array[start=0:stop-1=last:step=1, start=0:stop-1=last:step=1]

In [10]:
array[0,2] # row 0 and col 2

np.int64(2)

In [11]:
array[0, -1] # row 0 and col -1

np.int64(3)

In [13]:
array[0, ::] # row 0 and all the columns

array([0, 1, 2, 3])

In [14]:
array[::, ::] # every rows anf columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
array[::, -1] # all rows and the last column

array([ 3,  7, 11])

In [16]:
array[0::2, ::] # from row 0 step 2 and all the columns

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [17]:
array[::, 0::2] # all the rows and from column 0 step 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [18]:
array[1:3:1, 1:3:1] # rows 1,2 and col 1,2

array([[ 5,  6],
       [ 9, 10]])

In [19]:
array[::, 1:3:1] # all the rows and col 1,2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [20]:
array[0:2:1, -2::] # row 0,1 and col -2,-1

array([[2, 3],
       [6, 7]])

In [21]:
array[1:3, :2] # row 0,1 and col 0,1

array([[4, 5],
       [8, 9]])