In [1]:
import numpy as np

## Row Matrix --> It's a matrix with only one row

In [2]:
row = np.arange(1, 20).reshape((1, -1))
print(row)
print(row.shape)
print(row.ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 19)
2


## Column Matrix --> It's a matrix with only one cloumn

In [4]:
column = np.arange(1, 10).reshape((-1, 1))
print(column)
print(column.shape)
print(column.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)
2


## Squared Matrix --> A matrix with equal rows and columns

In [6]:
sqr_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(sqr_matrix)
print(sqr_matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## One & Oneslike --> A matrix that all of the items are '1'

In [8]:
np.ones((3, 4)) # make a new matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
### Ones Like --> change the items of an exicting matrix 
np.ones_like(sqr_matrix)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Zeros --> It work like ones but the items are '0'

In [10]:
print(np.zeros((3, 4)))

print(np.zeros_like(sqr_matrix))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Identity --> Make an squre matrix, the main diameter full with '1' and the other items are '0'

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## diagonal --> An squre matrix how all the items are '0' instead of the main diameter

In [14]:
np.diag([1, 2, 3, 4, 5, 6, 7]) # It works with list!

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [15]:
np.diag(sqr_matrix) # Return the main diameter items

array([1, 5, 9])

In [16]:
np.diag(np.fliplr(sqr_matrix)) # Return not main diameter items

array([3, 5, 7])

## Triangle Up --> All the items under the main diameter are '0'

In [17]:
np.triu(sqr_matrix)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

## Triangle Low --> All the items abow the main diameter are '0'

In [18]:
np.tril(sqr_matrix)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])