# Creating Numpy Arrays

In [1]:
import numpy as np

## zeros()

In [2]:
# Creat an array filled with zeros

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# Creat a 2D array of zeros

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones()

In [6]:
# Creat an array filled with ones

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
# Creat a 2D array of ones

In [9]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## full()

In [10]:
# Creatg an array filled with a specific value

In [11]:
np.full((2, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

## empty()

In [12]:
# Creat an uninitialalized array

In [13]:
np.empty((2,3))

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

## arange()

In [16]:
# Creat values from 0 to 9

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Start, stop, step

In [19]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [20]:
# Negative steps

In [21]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

### important : Stop is not included

## linspace()

In [24]:
# Creat 5 evenly spaced values between 0 and 10

In [23]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
# Creat 11 evenly spaced values between 0 and 100

In [26]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
# Difference :
#    arange() : specify the step
#    linespace() : specify the number of values

## eye()

In [28]:
# Create an identity matrix

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Specifyind dtype

In [30]:
# Creat an integer array

In [31]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [32]:
# Creat a float array

In [34]:
np.ones(5, dtype = float)

array([1., 1., 1., 1., 1.])

In [35]:
# Creat a boolean array

In [36]:
np.zeros(5, dtype = bool)

array([False, False, False, False, False])