# NumPy Indexing & Slicing

## 1D Array - Indexing

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

In [3]:
# First element - Last element - Third element

In [4]:
arr[0]

np.int64(10)

In [5]:
arr[-1]

np.int64(50)

In [6]:
arr[2]

np.int64(30)

In [7]:
# Changing value

In [8]:
arr[1] = 25
arr

array([10, 25, 30, 40, 50])

## 1D Array Slicing

In [10]:
# arr[start:stop]
arr[1:4]

array([25, 30, 40])

In [11]:
# From the begining
arr[:3]

array([10, 25, 30])

In [13]:
# To the end
arr[2:]

array([30, 40, 50])

In [15]:
# Every Second element
arr[::2]

array([10, 30, 50])

In [16]:
# Revers the array
arr[::-1]

array([50, 40, 30, 25, 10])

## 2d Array Indexing

In [17]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [18]:
# First row
arr[0]

array([10, 20, 30])

In [19]:
# First element of first row
arr[0, 0]

np.int64(10)

In [22]:
# Row 2 column 3
arr[1,2]

np.int64(60)

In [23]:
# Last element
arr[-1, -1]

np.int64(90)

## Selecting Rows & Columns

In [24]:
# First , Second and last row

In [26]:
arr[0,:]

array([10, 20, 30])

In [27]:
arr[1, :]

array([40, 50, 60])

In [28]:
arr[-1, :]

array([70, 80, 90])

In [29]:
# First, Second and last column

In [30]:
arr[: , 0]

array([10, 40, 70])

In [31]:
arr[:,1]

array([20, 50, 80])

In [32]:
arr[:, -1]

array([30, 60, 90])

## 2D Slicing

In [35]:
# Row 1-2, column 1-2
arr[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [36]:
# First 2 rows
arr[:2,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [38]:
# Last two columns
arr[:, -2:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [39]:
# Every second row
arr[::2,:]

array([[10, 20, 30],
       [70, 80, 90]])

In [40]:
# Every second column
arr[:,::2]

array([[10, 30],
       [40, 60],
       [70, 90]])

# Boolean Indexing

In [41]:
arr = np.array([10, 25, 30, 15, 40, 5])

In [42]:
# Creat a boolean mask
arr > 20

array([False,  True,  True, False,  True, False])

In [43]:
# Select values greater than 20
arr[arr > 20]

array([25, 30, 40])

## Multiple Conditions

In [44]:
# AND condition

In [45]:
arr[(arr > 10) & (arr < 30)]

array([25, 15])

In [46]:
# NOT condition

In [47]:
arr[~(arr > 20)]

array([10, 15,  5])

In [48]:
# OR condition

In [49]:
arr[(arr < 10) | (arr > 30)]

array([40,  5])

## np.where()

In [50]:
arr = np.array([10, 25, 30, 15, 40])

In [52]:
# Return indices where condition is True
np.where(arr>20)

(array([1, 2, 4]),)

In [53]:
# Replace values based on a condition
np.where(arr>20, 1, 0)

array([0, 1, 1, 0, 1])

In [ ]:
# condition --> True value --> False value