# Basic Arithmetic

In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [4]:
# Addition
arr + 5

array([15, 25, 35, 45, 55])

In [5]:
# Subtraction
arr - 5

array([ 5, 15, 25, 35, 45])

In [6]:
# Multiplication
arr * 2

array([ 20,  40,  60,  80, 100])

In [7]:
# Division
arr / 2

array([ 5., 10., 15., 20., 25.])

In [8]:
# Floor division
arr // 2

array([ 5, 10, 15, 20, 25])

In [9]:
# Modulo
arr % 3

array([1, 2, 0, 1, 2])

In [10]:
# Power
arr **2

array([ 100,  400,  900, 1600, 2500])

# Element wise Operations

In [12]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [13]:
# Element-wise additioin
a + b

array([11, 22, 33])

In [14]:
# Element-wise multiplication
a * b

array([10, 40, 90])

In [15]:
# Element-wise division
a / b

array([10., 10., 10.])

# Comparison Operators

In [16]:
arr = np.array([10, 20, 30, 40, 50])

In [17]:
# Greater than
arr > 25

array([False, False,  True,  True,  True])

In [18]:
# Less than
arr < 25

array([ True,  True, False, False, False])

In [19]:
# Equal
arr == 30

array([False, False,  True, False, False])

In [20]:
# Not equal
arr != 30

array([ True,  True, False,  True,  True])

# Basic Mathematical Functions

In [21]:
# Absolute value
np.abs([-10, -5, 0, 5, 10])

array([10,  5,  0,  5, 10])

In [22]:
# Power
np.power([2, 3, 4], 2)

array([ 4,  9, 16])

In [24]:
# Square root
np.sqrt([9, 16, 25])

array([3., 4., 5.])

In [25]:
# Exponential
np.exp([1, 2, 3])

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
# Natural logarithm
np.log([1, np.e, np.e**2])

array([0., 1., 2.])

In [28]:
# Base-10 logarithm
np.log10([1, 10, 100, 1000])

array([0., 1., 2., 3.])

# Rounding Functions

In [33]:
arr = np.array([1.231, 2.5, 3.7, 4.9])

In [34]:
# Round values
np.round(arr)

array([1., 2., 4., 5.])

In [35]:
# Round to 2 decimal placees
np.round(arr, 2)

array([1.23, 2.5 , 3.7 , 4.9 ])

In [36]:
# Round down
np.floor(arr)

array([1., 2., 3., 4.])

In [37]:
# Round up
np.ceil(arr)

array([2., 3., 4., 5.])

# Aggregation Functions

In [38]:
arr = np.array([10, 20, 30, 40, 50])

In [39]:
# # Minimum value
np.min(arr)

np.int64(10)

In [40]:
# Maximum value
np.max(arr)

np.int64(50)

In [41]:
# Sum of values
np.sum(arr)

np.int64(150)

In [42]:
# Mean
np.mean(arr)

np.float64(30.0)

### Usefull Shortcuts

In [48]:
print(arr.min(),
      arr.max(),
      arr.sum(),
      arr.mean()
     )

10 50 150 30.0


## Example - Data Analysis

In [49]:
temp = np.array([18.5, 21.2, 25.7, 19.8, 30.1])

In [50]:
# Convert Celsius to Fahrenheit
temp * 9 /5 + 32

array([65.3 , 70.16, 78.26, 67.64, 86.18])

In [51]:
# Avrage Temp
temp.mean()

np.float64(23.060000000000002)

In [52]:
# Highest and Lowest temp
print(temp.max(),
     temp.min())

30.1 18.5
