# NumPy Axis & Aggregation

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]])

In [3]:
# Understandin axis
# axis = 0 --> Down the rows -->
# calculate for each column
# axis = 1 --> Across the columns -->
# calculate for each row

## sum()

In [5]:
# Sum of all values
np.sum(arr)

np.int64(450)

In [8]:
# Sum of each column
np.sum(arr, axis = 0)

array([120, 150, 180])

In [9]:
# Sum of each row
np.sum(arr, axis = 1)

array([ 60, 150, 240])

## mean()

In [10]:
np.mean(arr)

np.float64(50.0)

In [11]:
# Mean of each column
np.mean(arr, axis = 0)

array([40., 50., 60.])

In [12]:
# Mean of each row
np.mean(arr, axis = 1)

array([20., 50., 80.])

## min() / max()

In [13]:
# Minimu of each column
np.min(arr, axis = 0)

array([10, 20, 30])

In [14]:
# Maximum of each row
np.max(arr, axis = 1)

array([30, 60, 90])

# argmmin() / argmax()

In [15]:
arr = ([10, 50, 20, 80, 30])

In [16]:
# Index of minimum value
np.argmin(arr)

np.int64(0)

In [17]:
# Index of maximum value
np.argmax(arr)

np.int64(3)

In [18]:
arr = ([
    [10, 50, 20],
    [80, 30, 60]])

In [19]:
# Index of maximum value for each row
np.argmax(arr, axis = 1)

array([1, 0])

In [20]:
# Index of minimum value for each column
np.argmin(arr, axis = 0)

array([0, 1, 0])

## cumsum()

In [21]:
arr = np.array([10, 20, 30, 40])

In [23]:
# Cumulative sum
np.cumsum(arr)

array([ 10,  30,  60, 100])

## cumprod()

In [25]:
# Cumulative prod
np.cumprod(arr)

array([    10,    200,   6000, 240000])

## diff()

In [26]:
arr = np.array([10, 15, 25, 20,  30])

In [27]:
# Diffrence between consecutive values
np.diff(arr)

array([ 5, 10, -5, 10])

# Exaple - Data Analysis

In [28]:
sales = np.array([[100, 120, 150],
                  [200, 180, 220],
                  [150, 170, 160]
                 ])

In [29]:
# Total sales for each product
sales.sum(axis = 1)

array([370, 600, 480])

In [30]:
# Average sales for each product
sales.mean(axis = 1)

array([123.33333333, 200.        , 160.        ])