# NumPy Array Reshaping

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
# Reshape to 3 rows and 4 columns
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
# Reshape to 4 rows and 3 columns
arr.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Using

In [5]:
# Automaticlly calculate the number of rows
arr.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# Automaticlly calculate the number of columns
arr.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## flatten()

In [7]:
# Convert to 1D array
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## ravel()

In [8]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
# flatten() --> returns a copy
# ravel() --> usually returns a view

## tranpose()

In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Tranpose the array
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## expand_dims()

In [14]:
arr = np.array([1, 2, 3, 4])
arr.shape

(4,)

In [16]:
# Add a new axis
np.expand_dims(arr, axis = 0)

array([[1, 2, 3, 4]])

In [17]:
# Add a new axis
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

## squeeze()

In [18]:
arr = np.array([[1, 2, 3, 4]])
arr.shape

(1, 4)

In [21]:
# Remove dimensions of sixze 1
np.squeeze(arr).shape

(4,)

# Example-Data Analysis

In [22]:
data = np.arange(1, 13)

In [23]:
# Convert one-dimensional data into a table
data.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# Conver the table back to 1D
data.reshape(3, 4).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])