# Numpy Array Concatenation & Splitting

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b= np.array([4, 5,  6])

In [3]:
# Join arrays
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

## 2D Arrays

In [4]:
a = np.array([
    [1, 2],
    [3, 4]
])
b= np.array([
    [5, 6],
    [7, 8]
])


In [6]:
# Concatenate rows
np.concatenate([a, b], axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
# Concatenate columns
np.concatenate([a, b], axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## vstack() / hstack()

In [8]:
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## stack()

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5,  6])

In [11]:
# Stavk along a new axis
np.stack([a, b], axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Stavk along a new axis
np.stack([a, b], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
# Check the new shape
np.stack([a, b], axis = 0).shape

(2, 3)

# Splitting Arrays

## split()

In [15]:
arr =np.array([1, 2 ,3, 4, 5, 6])

In [16]:
# Split into 3 equal parts
np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [17]:
# Split into 2 equal parts
np.split(arr, 2)

[array([1, 2, 3]), array([4, 5, 6])]

## array_split()

In [18]:
arr =np.array([1, 2 ,3, 4, 5])

In [20]:
# Split into 2  parts
np.array_split(arr, 2)

[array([1, 2, 3]), array([4, 5])]

# 2D Splitting

In [22]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# Split rows
np.split(arr, 3, axis = 0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [24]:
# Split columns
np.split(arr, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

# Example - Data Analysis

In [25]:
data = np.arange(1, 11)

In [26]:
# Split data into training and testing parts
train, test = np.split(data, [7])

In [27]:
train

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
test

array([ 8,  9, 10])