# NumPy Broadcasting

## Basic Broadcasting

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40])

In [3]:
# # Add a scaler to all elements
arr + 5

array([15, 25, 35, 45])

In [4]:
# Multiple all elements
arr *2

array([20, 40, 60, 80])

## Array + Array

In [6]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [8]:
a + b

array([11, 22, 33])

In [9]:
# Element-wise multipilication
a * b

array([10, 40, 90])

## 2D Array + Scaler

In [10]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
arr + 10

array([[20, 30, 40],
       [50, 60, 70]])

In [11]:
# Multiple all elemnets 
arr *2

array([[ 20,  40,  60],
       [ 80, 100, 120]])

## 2D Array + 1D Array

In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
values = np.array([1, 2, 3])
arr +values

array([[11, 22, 33],
       [41, 52, 63]])

In [13]:
values = np.array([
    [10],
    [20]
])

arr + values

array([[20, 30, 40],
       [60, 70, 80]])

# Example - Data Analysis

In [14]:
temp = np.array([
    [20, 22, 25],
    [15, 18, 21],
    [30, 32, 35]
])


In [15]:
# Convert Celsius to Fahrenheit
temp *9 / 5 + 32

array([[68. , 71.6, 77. ],
       [59. , 64.4, 69.8],
       [86. , 89.6, 95. ]])