# NumPy Missing Values & Special Values

## NaN

In [2]:
import numpy as np
arr = np.array([10, 20, np.nan, 40, 50])
arr

array([10., 20., nan, 40., 50.])

In [4]:
# Check for NaN
np.isnan(arr)

array([False, False,  True, False, False])

In [5]:
# Select NaN values
arr[np.isnan(arr)]

array([nan])

In [7]:
# Select non-NaN values
arr[~np.isnan(arr)]

array([10., 20., 40., 50.])

## NaN and Calculations

In [9]:
# NaN affect calculates
np.mean(arr)

np.float64(nan)

In [10]:
# Mean ignoring NaN
np.nanmean(arr)

np.float64(30.0)

In [12]:
# Sum ignoring NaN
np.nansum(arr)

np.float64(120.0)

In [13]:
# Minimum ignoring NaN
np.nanmin(arr)

np.float64(10.0)

In [14]:
# Maximum ignoring NaN
np.nanmax(arr)

np.float64(50.0)

## isnan() + Filtering

In [15]:
arr = np.array([10, 20, np.nan, 30, np.nan, 40])

In [16]:
# Remove NaN values
clean_arr = arr[~np.isnan(arr)]
clean_arr

array([10., 20., 30., 40.])

# Replacing NaN

In [17]:
arr = np.array([10, 20, np.nan, 40, 50])

In [19]:
# replace NaN with 0
np.nan_to_num(arr, nan = 0)

array([10., 20.,  0., 40., 50.])

## None

In [20]:
arr = np.array([10, 20, None, 40, 50])

In [21]:
# Check dtype
arr.dtype

dtype('O')

In [22]:
# Check for None
arr == None

array([False, False,  True, False, False])

# Example - Data Analysis

In [23]:
temp = np.array([20.5, 22.1, np.nan, 18.7, np.nan, 25.3])

In [24]:
# Count missing values
np.isnan(temp).sum()

np.int64(2)

In [26]:
# Mean without missing values
np.nanmean(temp)

np.float64(21.65)

In [27]:
# Remove missing values
temp[~np.isnan(temp)]

array([20.5, 22.1, 18.7, 25.3])