# NumPy Statistical Functions

In [6]:
import numpy as np

In [7]:
data = np.array([10, 20, 30, 40, 50])

# Mean

In [8]:
np.mean(data)

np.float64(30.0)

# Median

In [9]:
np.median(data)

np.float64(30.0)

# Variance

In [10]:
np.var(data)

np.float64(200.0)

# Standard deviation

In [11]:
np.std(data)

np.float64(14.142135623730951)

# Percentile

In [13]:
# 25th percentile
np.percentile(data, 25)

np.float64(20.0)

In [14]:
# 50th percentile
np.percentile(data, 50)

np.float64(30.0)

In [15]:
# 75th percentile
np.percentile(data, 75)

np.float64(40.0)

# Quantile

In [16]:
# 25th quantile
np.quantile(data, 0.25)

np.float64(20.0)

In [17]:
# 50th quantile
np.quantile(data, 0.5)

np.float64(30.0)

In [18]:
# 75th quantile
np.quantile(data, 0.75)

np.float64(40.0)

In [19]:
# percentile --> 0 to 100
# quantile --> 0 to 1

# Correlation

In [29]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

In [30]:
# corelation matrix
np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

In [31]:
# Corelation coefficient
np.corrcoef(x, y)[0, 1]

np.float64(0.9999999999999999)

# Covariance

In [32]:
# Covariance matrix
np.cov(x, y)

array([[ 2.5,  5. ],
       [ 5. , 10. ]])

In [33]:
# Covariance value
np.cov(x, y)[0, 1]

np.float64(5.0)

# Statistics Along an Axis

In [34]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80 ,90]
])

In [35]:
# Mean of eaech column
np.mean(data, axis = 0)

array([40., 50., 60.])

In [36]:
# Median for each column
np.median(data, axis = 0)

array([40., 50., 60.])

In [37]:
# Standard diviation of each column
np.std(data, axis = 0)

array([24.49489743, 24.49489743, 24.49489743])

In [38]:
# Mean of each row
np.mean(data, axis = 1)

array([20., 50., 80.])

# Example - Data Analysis

In [39]:
scores = np.array([65, 72, 80, 85, 90, 95, 100])

In [43]:
# Basic statistics
print('Mean',np.mean(scores))
print('Median',np.median(scores) )
print('Std',np.std(scores) )
print('Min',np.min(scores) )
print('Max',np.max(scores) )

Mean 83.85714285714286
Median 85.0
Std 11.55642766637525
Min 65
Max 100


In [45]:
# Quantiles
q1 = np.percentile(scores, 25)
q2 = np.percentile(scores, 50)
q3 = np.percentile(scores, 75)
q1, q2, q3

(np.float64(76.0), np.float64(85.0), np.float64(92.5))