# Random Generator

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()

In [3]:
rng.random()

0.40023024966154674

In [4]:
# Random float between 0 and 1
rng.random(5)

array([0.19586104, 0.14409223, 0.11932483, 0.02281254, 0.70932985])

## Seed

In [5]:
# Same seed ==? same result
rng = np.random.default_rng(42)
rng.random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

## Random Integers

In [8]:
rng.integers(1, 10)

np.int64(9)

In [10]:
# 5 random integers
rng.integers(1, 10, size = 5)

array([7, 7, 7, 8, 5])

## Random Floats

In [11]:
rng.uniform(10, 20, size = 5)

array([14.50385938, 13.70798024, 19.26764989, 16.4386512 , 18.22761613])

## Normal Distribution

In [12]:
rng.normal(loc=50, scale=10, size=5)

array([54.67509342, 41.40707537, 53.68750784, 40.41117399, 58.78450301])

In [13]:
# loc --> mean
# scale --> standard diviation
# size --> size

In [14]:
temp = rng.normal(loc=20, scale=5, size=100)
temp

array([19.75037045, 19.07568818, 16.59535228, 26.11270669, 19.22735259,
       17.85836089, 18.23933225, 22.66154593, 21.82722032, 22.06366306,
       22.15410502, 30.708238  , 17.96792492, 17.43878635, 15.93113636,
       23.07989711, 25.64486146, 19.43026271, 15.79921762, 15.87759392,
       23.25296394, 23.71627086, 22.71577134, 16.67245146, 21.16080662,
       20.58342905, 21.09344298, 24.35714389, 21.11797774, 23.39456782,
       20.33789535, 21.44559699, 23.15644113, 12.7142209 , 18.40164392,
       17.64813673, 16.80561076, 18.62428874, 27.47470656, 15.67084442,
       24.84139177, 11.58565114, 18.32557485, 20.81376533, 22.93111166,
       23.5561329 , 23.96673618, 18.25637464, 17.68824104, 24.28987941,
       19.04347838, 13.62156838, 14.33356393, 15.40273857, 22.48580372,
       20.71212868, 23.45242677, 17.86373677, 20.79269846, 23.12795197,
       18.4532673 , 22.28387619, 16.69037029, 18.18473077, 18.09131053,
       14.02080177, 22.4348624 , 17.6529883 , 20.06247059, 22.40

## Random Choice

In [15]:
cities = np.array(['Baku', 'Tabriz', 'Tehran', 'Shiraz'])
rng.choice(cities)

np.str_('Baku')

In [16]:
# Select 5 values
rng.choice(cities, size = 5)

array(['Baku', 'Tehran', 'Tehran', 'Baku', 'Shiraz'], dtype='<U6')

In [17]:
rng.choice(cities, size = 3, replace = False)

array(['Tehran', 'Shiraz', 'Baku'], dtype='<U6')

## Shuffle

In [19]:
x = np.array([1, 2, 3, 4, 5])
rng.shuffle(x)
x

array([2, 3, 1, 5, 4])

# Random Sampling

In [21]:
data = np.arange(100)
sample = rng.choice(data, size = 10, replace = False)
sample

array([91, 54, 57, 58, 84, 32, 28,  2, 42, 15])

## Weighted Random Choice !!

In [24]:
items = np.array(['A', 'B', 'C'])
probabilities = [0.1, 0.2, 0.7]
rng.choice(
    items,
    size= 10,
    p = probabilities
)

array(['C', 'B', 'A', 'C', 'C', 'C', 'C', 'C', 'C', 'B'], dtype='<U1')