# Sorting & Searching

In [2]:
import numpy as np

## Sorting

In [3]:
x= np.array([5, 2, 8, 1, 9, 3])
np.sort(x)

array([1, 2, 3, 5, 8, 9])

In [5]:
# Descending order

In [7]:
np.sort(x)[::-1]

array([9, 8, 5, 3, 2, 1])

# Sorting 2D Arrays

In [8]:
x= ([
    [5, 2, 8],
    [1, 9, 3]
])

np.sort(x)

array([[2, 5, 8],
       [1, 3, 9]])

In [9]:
# Sort by column

In [10]:
np.sort(x, axis = 0)

array([[1, 2, 3],
       [5, 9, 8]])

## argsore()

In [11]:
x = np.array([50, 20, 80, 10])

idx = np.argsort(x)
idx

array([3, 1, 0, 2])

In [12]:
x[idx]

array([10, 20, 50, 80])

In [13]:
names = np.array(['Ali', 'Sara', 'Reza', 'Mina'])
scores = np.array([80, 95, 70, 100])
idx = np.argsort(scores)
idx

array([2, 0, 1, 3])

In [14]:
names[idx]

array(['Reza', 'Ali', 'Sara', 'Mina'], dtype='<U4')

## Unique()

In [15]:
x = np.array([1, 2, 2, 3, 3, 3, 4])
np.unique(x)

array([1, 2, 3, 4])

In [17]:
values, counts = np.unique(x, return_counts = True)

print(values)
print(counts)

[1 2 3 4]
[1 2 3 1]


## isin()

In [18]:
x = np.array([10, 20, 30, 40, 50])
np.isin(x, [20, 40])

array([False,  True, False,  True, False])

In [19]:
x[np.isin(x, [20, 40])]

array([20, 40])

## nonzero()

In [20]:
x = np.array([0, 5, 0, 8, 3])
np.nonzero(x)

(array([1, 3, 4]),)