# Multidimensional Arrays & Matrix Operations

In [1]:
import numpy as np

## 2D Array

In [3]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Shape of matrix
A.shape

(2, 3)

## Matrix Tranpose

In [6]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Matrix Multiplication

In [7]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
A @ B

array([[19, 22],
       [43, 50]])

In [9]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [10]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [11]:
# row[0, 0] * column[0, 0] + row[0, 0] * column[0, 1]

## Matrix + Vector

In [12]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

v = np.array([1, 2, 3])

A +v

array([[11, 22, 33],
       [41, 52, 63]])