# NumPy in Data Analysis

In [6]:
import numpy as np

## Creat Sample Data

In [7]:
data = np.array([12, 15, 18, 21, 25, 30, 35, 40, 45, 50])

## Basic Statistics

In [8]:
data.mean()

np.float64(29.1)

In [9]:
data.min()

np.int64(12)

In [10]:
data.max()

np.int64(50)

In [11]:
data.std()

np.float64(12.41329931968129)

## Filtering Data

In [12]:
data[data > 30]

array([35, 40, 45, 50])

In [13]:
data[(data > 20) & (data <= 40)]

array([21, 25, 30, 35, 40])

## Handling Missing Values

In [14]:
data = np.array([10, 20, np.nan, 30, 40, np.nan])

In [17]:
np.isnan(data)

array([False, False,  True, False, False,  True])

In [18]:
np.nanmean(data)

np.float64(25.0)

## Detecting Logical Outliers

In [20]:
temp = np.array([10, 25, 35, 100, -80, 20])

mask = ((temp < -50) | (temp > 60))

temp[mask]

array([100, -80])

In [23]:
temp = temp.astype(float)

temp[mask] = np.nan
temp

array([10., 25., 35., nan, nan, 20.])

## Normalization

In [25]:
# x_normalization = (x - min) / (max - min)

In [24]:
x = np.array([10, 20, 30, 40, 50])

x_norm = ((x - x.min()) / (x.max() - x.min()))

x_norm

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Standardization

In [26]:
# z = (x - mean) / std

In [28]:
x = np.array([10, 20, 30, 40, 50])
x_std = (x- x.mean() / x.std())

x_std

array([ 7.87867966, 17.87867966, 27.87867966, 37.87867966, 47.87867966])

## Percentiles & Quantiles

In [29]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
np.percentile(x, 25)

np.float64(32.5)

In [30]:
np.percentile(x, [25, 50, 75])

array([32.5, 55. , 77.5])

In [31]:
np.quantile(x, [0.25 , 0.5, 0.75])

array([32.5, 55. , 77.5])

## Finding Relationships

In [34]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

# Simple Data Analysis Workflow

In [36]:
# 1. Loead Data
data = np.array([10, 15, 20, 25, 30, 100])

# 2. Detect logical outliers
mask = data > 50

# 3. Replace invalid values
data = data.astype(float)
data[mask] = np.nan

# 4. Calculate statistics

mean = np.nanmean(data)
median = np.nanmedian(data)

# 5. Normalize
normalized = ((data - np.nanmin(data)) / np.nanmax(data) - np.nanmin(data))

mean, median, normalized

(np.float64(20.0),
 np.float64(20.0),
 array([-10.        ,  -9.83333333,  -9.66666667,  -9.5       ,
         -9.33333333,          nan]))